FROM node:22-alpine 

WORKDIR /app

ARG DATABASE_URL

COPY ./frontend/package.json .

RUN npm install

COPY ./frontend .

COPY ./prisma .

RUN npm install prisma

RUN npx prisma generate

# even in the docker build nextjs require the DB connection

RUN DATABASE_URL=${DATABASE_URL} npm run build

EXPOSE 3000

CMD [ "npm" , "start"]